version: '3.8'

services:
  # قاعدة البيانات MySQL
  mysql:
    image: mysql:8.0
    container_name: echoops_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: echoops_root_password
      MYSQL_DATABASE: echoops_crm
      MYSQL_USER: echoops_user
      MYSQL_PASSWORD: echoops_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - echoops_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis للتخزين المؤقت
  redis:
    image: redis:7-alpine
    container_name: echoops_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - echoops_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10

  # الخادم الخلفي NestJS
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: echoops_backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: echoops_user
      DB_PASSWORD: echoops_password
      DB_DATABASE: echoops_crm
      REDIS_HOST: redis
      REDIS_PORT: 6379
      JWT_SECRET: echoops_jwt_secret_key_production
      JWT_EXPIRES_IN: 24h
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - echoops_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      timeout: 20s
      retries: 10

  # الواجهة الأمامية React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: echoops_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: http://localhost:3001
      VITE_APP_NAME: EchoOps CRM
      VITE_APP_VERSION: 1.0.0
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - echoops_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      timeout: 20s
      retries: 10

  # Nginx كـ Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: echoops_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - echoops_network

  # PhpMyAdmin لإدارة قاعدة البيانات
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: echoops_phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: echoops_user
      PMA_PASSWORD: echoops_password
      MYSQL_ROOT_PASSWORD: echoops_root_password
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - echoops_network

  # Redis Commander لإدارة Redis
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: echoops_redis_commander
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - echoops_network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  echoops_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
